//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `music3.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.ceri.iceclient.Music3;

/** @hidden */
public class _MusicService3PrxI extends com.zeroc.Ice._ObjectPrxI implements MusicService3Prx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
