//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `music3.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.ceri.iceclient.Music3;

public interface MusicService3Prx extends com.zeroc.Ice.ObjectPrx
{
    default byte[] play(String fileName)
    {
        return play(fileName, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default byte[] play(String fileName, java.util.Map<String, String> context)
    {
        return _iceI_playAsync(fileName, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<byte[]> playAsync(String fileName)
    {
        return _iceI_playAsync(fileName, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<byte[]> playAsync(String fileName, java.util.Map<String, String> context)
    {
        return _iceI_playAsync(fileName, context, false);
    }

    /**
     * @hidden
     * @param iceP_fileName -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<byte[]> _iceI_playAsync(String iceP_fileName, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<byte[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "play", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_fileName);
                 }, istr -> {
                     byte[] ret;
                     ret = istr.readByteSeq();
                     return ret;
                 });
        return f;
    }

    default void stop()
    {
        stop(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void stop(java.util.Map<String, String> context)
    {
        _iceI_stopAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> stopAsync()
    {
        return _iceI_stopAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> stopAsync(java.util.Map<String, String> context)
    {
        return _iceI_stopAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_stopAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "stop", null, sync, null);
        f.invoke(false, context, null, null, null);
        return f;
    }

    default void storeMusicFile(byte[] fileData, String fileName)
    {
        storeMusicFile(fileData, fileName, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void storeMusicFile(byte[] fileData, String fileName, java.util.Map<String, String> context)
    {
        _iceI_storeMusicFileAsync(fileData, fileName, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> storeMusicFileAsync(byte[] fileData, String fileName)
    {
        return _iceI_storeMusicFileAsync(fileData, fileName, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> storeMusicFileAsync(byte[] fileData, String fileName, java.util.Map<String, String> context)
    {
        return _iceI_storeMusicFileAsync(fileData, fileName, context, false);
    }

    /**
     * @hidden
     * @param iceP_fileData -
     * @param iceP_fileName -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_storeMusicFileAsync(byte[] iceP_fileData, String iceP_fileName, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "storeMusicFile", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeByteSeq(iceP_fileData);
                     ostr.writeString(iceP_fileName);
                 }, null);
        return f;
    }

    default void deleteMusicFile(String fileName)
    {
        deleteMusicFile(fileName, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void deleteMusicFile(String fileName, java.util.Map<String, String> context)
    {
        _iceI_deleteMusicFileAsync(fileName, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> deleteMusicFileAsync(String fileName)
    {
        return _iceI_deleteMusicFileAsync(fileName, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> deleteMusicFileAsync(String fileName, java.util.Map<String, String> context)
    {
        return _iceI_deleteMusicFileAsync(fileName, context, false);
    }

    /**
     * @hidden
     * @param iceP_fileName -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_deleteMusicFileAsync(String iceP_fileName, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "deleteMusicFile", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_fileName);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MusicService3Prx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), MusicService3Prx.class, _MusicService3PrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MusicService3Prx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), MusicService3Prx.class, _MusicService3PrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MusicService3Prx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), MusicService3Prx.class, _MusicService3PrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MusicService3Prx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), MusicService3Prx.class, _MusicService3PrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static MusicService3Prx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, MusicService3Prx.class, _MusicService3PrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static MusicService3Prx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, MusicService3Prx.class, _MusicService3PrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default MusicService3Prx ice_context(java.util.Map<String, String> newContext)
    {
        return (MusicService3Prx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default MusicService3Prx ice_adapterId(String newAdapterId)
    {
        return (MusicService3Prx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default MusicService3Prx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (MusicService3Prx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default MusicService3Prx ice_locatorCacheTimeout(int newTimeout)
    {
        return (MusicService3Prx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default MusicService3Prx ice_invocationTimeout(int newTimeout)
    {
        return (MusicService3Prx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default MusicService3Prx ice_connectionCached(boolean newCache)
    {
        return (MusicService3Prx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default MusicService3Prx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (MusicService3Prx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default MusicService3Prx ice_secure(boolean b)
    {
        return (MusicService3Prx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default MusicService3Prx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (MusicService3Prx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default MusicService3Prx ice_preferSecure(boolean b)
    {
        return (MusicService3Prx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default MusicService3Prx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (MusicService3Prx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default MusicService3Prx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (MusicService3Prx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default MusicService3Prx ice_collocationOptimized(boolean b)
    {
        return (MusicService3Prx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default MusicService3Prx ice_twoway()
    {
        return (MusicService3Prx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default MusicService3Prx ice_oneway()
    {
        return (MusicService3Prx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default MusicService3Prx ice_batchOneway()
    {
        return (MusicService3Prx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default MusicService3Prx ice_datagram()
    {
        return (MusicService3Prx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default MusicService3Prx ice_batchDatagram()
    {
        return (MusicService3Prx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default MusicService3Prx ice_compress(boolean co)
    {
        return (MusicService3Prx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default MusicService3Prx ice_timeout(int t)
    {
        return (MusicService3Prx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default MusicService3Prx ice_connectionId(String connectionId)
    {
        return (MusicService3Prx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default MusicService3Prx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (MusicService3Prx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::Music3::MusicService3";
    }
}
