//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `music2.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.ceri.iceclient.Music2;

/** @hidden */
public class _MusicService2PrxI extends com.zeroc.Ice._ObjectPrxI implements MusicService2Prx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
