//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `music2.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.ceri.iceclient.Music2;

/**
 * Helper class for marshaling/unmarshaling MusicDataSeq.
 **/
public final class MusicDataSeqHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, MusicData[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                MusicData.ice_write(ostr, v[i0]);
            }
        }
    }

    public static MusicData[] read(com.zeroc.Ice.InputStream istr)
    {
        final MusicData[] v;
        final int len0 = istr.readAndCheckSeqSize(7);
        v = new MusicData[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = MusicData.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<MusicData[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, MusicData[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            MusicDataSeqHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<MusicData[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            MusicData[] v;
            v = MusicDataSeqHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
