//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `music2.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.ceri.iceclient.Music2;

public class MusicData implements java.lang.Cloneable,
                                  java.io.Serializable
{
    public int id;

    public String title;

    public String artist;

    public String filePath;

    public MusicData()
    {
        this.title = "";
        this.artist = "";
        this.filePath = "";
    }

    public MusicData(int id, String title, String artist, String filePath)
    {
        this.id = id;
        this.title = title;
        this.artist = artist;
        this.filePath = filePath;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        MusicData r = null;
        if(rhs instanceof MusicData)
        {
            r = (MusicData)rhs;
        }

        if(r != null)
        {
            if(this.id != r.id)
            {
                return false;
            }
            if(this.title != r.title)
            {
                if(this.title == null || r.title == null || !this.title.equals(r.title))
                {
                    return false;
                }
            }
            if(this.artist != r.artist)
            {
                if(this.artist == null || r.artist == null || !this.artist.equals(r.artist))
                {
                    return false;
                }
            }
            if(this.filePath != r.filePath)
            {
                if(this.filePath == null || r.filePath == null || !this.filePath.equals(r.filePath))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Music2::MusicData");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, id);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, title);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, artist);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, filePath);
        return h_;
    }

    public MusicData clone()
    {
        MusicData c = null;
        try
        {
            c = (MusicData)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.id);
        ostr.writeString(this.title);
        ostr.writeString(this.artist);
        ostr.writeString(this.filePath);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.id = istr.readInt();
        this.title = istr.readString();
        this.artist = istr.readString();
        this.filePath = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, MusicData v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public MusicData ice_read(com.zeroc.Ice.InputStream istr)
    {
        MusicData v = new MusicData();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<MusicData> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, MusicData v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<MusicData> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(MusicData.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final MusicData _nullMarshalValue = new MusicData();

    /** @hidden */
    public static final long serialVersionUID = 1814421510L;
}
