//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `music1.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.ceri.iceclient.Music1;

/** @hidden */
public class _MusicServicePrxI extends com.zeroc.Ice._ObjectPrxI implements MusicServicePrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
